#!/usr/bin/env bash
# GENERATED by tools/regionharness/gen_harness.py -- DO NOT EDIT.
# Documentation-as-script: instrument the REAL CoarseAIR tree for region
# n4_umn_pes.pip_evaluation. Read it before running it; it modifies codes/.
#
# How CoarseAIR collects sources (config/cmake/add_sources.cmake, verified):
#   there is NO glob. Each directory's CMakeLists.txt calls add_sources() with an
#   explicit file list, which appends absolute paths to the global SRCS_LIST
#   property; the top-level CMakeLists.txt calls get_sources(SRCS) and builds
#   libcoarseair from that list. A new source file is therefore invisible to the
#   build until its name is added to src/PESs/CMakeLists.txt by hand. CMake's
#   Fortran dependency scanner orders the compilation, so position in the list
#   does not matter.
set -euo pipefail

REPO=${REPO:-/home/adolgert/dev/skateboard}
SB=${SB:-/home/adolgert/dev/skateboard/tools/serialbox/install}
CA=${CA:-/home/adolgert/dev/skateboard/codes/CoarseAIR}
GEN=${GEN:-/home/adolgert/dev/skateboard/tools/regionharness/cases/n4_umn_pes/gen}
HARNESS=$REPO/tools/regionharness/gen_harness.py
SPEC=$REPO/notes/regions/n4_umn_pes.yaml

# --- 0. regenerate (deterministic; no-op if already current)
python3 "$HARNESS" "$SPEC" --out-dir "$GEN"

# --- 1. patch the target in place (idempotent; reverse with --restore)
python3 "$HARNESS" "$SPEC" --patch
python3 "$HARNESS" "$SPEC" --check

# --- 2. drop the capture module into the tree and register it with CMake
cp "$GEN/n4pes_capture_mod.f90" "$CA/src/PESs/n4pes_capture_mod.F90"
if ! grep -q 'n4pes_capture_mod.F90' "$CA/src/PESs/CMakeLists.txt"; then
    python3 - "$CA/src/PESs/CMakeLists.txt" <<'PY'
import re, sys
p = sys.argv[1]
t = open(p).read()
# Insert into the first add_sources( ... ) list in this file.
t = re.sub(r'(add_sources\s*\(\s*\n)', r'\1  n4pes_capture_mod.F90\n', t, count=1)
open(p, 'w').write(t)
PY
fi

# --- 3. reconfigure so every compile sees the serialbox .mod files and every
#        link pulls the serialbox archives. SetFortranFlags.cmake *appends* to
#        CMAKE_Fortran_FLAGS, so a user value survives. CMAKE_Fortran_STANDARD_LIBRARIES
#        is already used by this project for -llapack -lblas; extend it.
cmake -S "$CA" -B "$CA/build" \
  -DCMAKE_BUILD_TYPE=release \
  -DCMAKE_Fortran_FLAGS="-I $SB/include" \
  -DCMAKE_Fortran_STANDARD_LIBRARIES="-llapack -lblas $SB/lib/libSerialboxFortran.a $SB/lib/libSerialboxC.a $SB/lib/libSerialboxCore.a -lstdc++ -lpthread"

# --- 4. rebuild
make -C "$CA/build" -j"$(nproc)"

# --- 5. capture. The instrumented binary is inert unless FTG_CAPTURE_N > 0.
cat <<EOF

Instrumented. To capture 3 calls starting at the 500th call to n4pes:

  export FTG_DATA_DIR=$REPO/ftgdata
  export FTG_CAPTURE_ROUND=500
  export FTG_CAPTURE_N=3
  <run the CoarseAIR case as usual>

Cases land in \$FTG_DATA_DIR/ftg_n4pes_test/rNNNN/{input,output}.
Then:  MODE=tree /home/adolgert/dev/skateboard/tools/regionharness/cases/n4_umn_pes/replay/build.sh
       /home/adolgert/dev/skateboard/tools/regionharness/cases/n4_umn_pes/replay/build/ftg_n4pes_test \$FTG_DATA_DIR/ftg_n4pes_test/r0500

To un-instrument:
  python3 "$HARNESS" "$SPEC" --restore
  rm -f "$CA/src/PESs/n4pes_capture_mod.F90"   # and remove its line from src/PESs/CMakeLists.txt
  git -C "$CA" diff -- src/PESs/N4_UMN_PES_Class.F90       # must be empty
EOF
