#!/usr/bin/env bash
# GENERATED by tools/regionharness/gen_harness.py -- DO NOT EDIT.
# Build the replay driver for region n4_umn_pes.pip_evaluation.
#
# MODE=tree (default): link the instrumented CoarseAIR build. The target module
#   comes from libcoarseair.a, so replay runs the *same object code* that
#   produced the capture -- the only mode in which bitwise equality is meaningful.
# MODE=copy: compile a patched copy of the target given by TARGET_SRC. Used to
#   validate the generator without touching codes/.
#
# Produces two binaries from the same source:
#   ftg_n4pes_test   plain
#   ftg_n4pes_poison -ffpe-trap=invalid, so a signaling NaN reaching arithmetic dies at
#              the offending instruction instead of propagating.
set -euo pipefail

REPO=${REPO:-/home/adolgert/dev/skateboard}
SB=${SB:-/home/adolgert/dev/skateboard/tools/serialbox/install}
CA=${CA:-$REPO/codes/CoarseAIR}
GEN=${GEN:-/home/adolgert/dev/skateboard/tools/regionharness/cases/n4_umn_pes/gen}
OUT=${OUT:-/home/adolgert/dev/skateboard/tools/regionharness/cases/n4_umn_pes/replay/build}
MODE=${MODE:-tree}
TARGET_SRC=${TARGET_SRC:-/home/adolgert/dev/skateboard/codes/CoarseAIR/src/PESs/N4_UMN_PES_Class.F90}

FLAGS="-cpp -fno-unsafe-math-optimizations -fdefault-double-8 -fdefault-real-8 -ffree-line-length-none -frealloc-lhs -O3 -fPIC -fbounds-check -fbacktrace"
LIBS_SB="$SB/lib/libSerialboxFortran.a $SB/lib/libSerialboxC.a $SB/lib/libSerialboxCore.a"

# Locate the build's module directory via a module the target USEs.
CA_MOD=${CA_MOD:-$(dirname "$(find "$CA/build" -name 'parameters_module.mod' | head -1)")}
CA_LIB=${CA_LIB:-$(find "$CA/build" -name 'libcoarseair.a' | head -1)}
if [ ! -d "$CA_MOD" ]; then
    echo "error: parameters_module.mod not found under $CA/build -- build CoarseAIR first" >&2
    exit 1
fi

mkdir -p "$OUT"
echo "MODE=$MODE  CA_MOD=$CA_MOD  CA_LIB=${CA_LIB:-<none>}"

# 1. capture module (needed by the patched target; harmless in the driver link)
gfortran $FLAGS -I "$SB/include" -J "$OUT" -c "$GEN/n4pes_capture_mod.f90" -o "$OUT/n4pes_capture_mod.o"

TARGET_OBJ=""
TARGET_MOD="$CA_MOD"
if [ "$MODE" = "copy" ]; then
    # -I $CA/src/PESs lets cpp resolve the target's #include "../qct.inc".
    gfortran $FLAGS -I "$CA/src/PESs" -I "$OUT" -I "$CA_MOD" -I "$SB/include" \
        -J "$OUT" -c "$TARGET_SRC" -o "$OUT/target.o"
    TARGET_OBJ="$OUT/target.o"
    TARGET_MOD="$OUT"
fi

# 2. driver, twice: the poison binary differs only by the trap flag.
gfortran $FLAGS -I "$TARGET_MOD" -I "$OUT" -I "$CA_MOD" -I "$SB/include" -J "$OUT" \
    -c "$GEN/ftg_n4pes_test.f90" -o "$OUT/driver.o"
gfortran $FLAGS -ffpe-trap=invalid -I "$TARGET_MOD" -I "$OUT" -I "$CA_MOD" -I "$SB/include" \
    -J "$OUT" -c "$GEN/ftg_n4pes_test.f90" -o "$OUT/driver_poison.o"

if [ "${COMPILE_ONLY:-0}" = "1" ] || [ -z "$CA_LIB" ]; then
    echo "objects built in $OUT (no link: COMPILE_ONLY or libcoarseair.a missing)"
    exit 0
fi

# 3. link
for pair in "driver.o:ftg_n4pes_test" "driver_poison.o:ftg_n4pes_poison"; do
    obj=${pair%%:*}; exe=${pair##*:}
    gfortran $FLAGS -o "$OUT/$exe" "$OUT/$obj" "$OUT/n4pes_capture_mod.o" $TARGET_OBJ \
        "$CA_LIB" $LIBS_SB -lstdc++ -lpthread -llapack -lblas
    echo "built $OUT/$exe"
done

echo
echo "run:  $OUT/ftg_n4pes_test   <FTG_DATA_DIR>/ftg_n4pes_test/rNNNN"
echo "      $OUT/ftg_n4pes_poison <FTG_DATA_DIR>/ftg_n4pes_test/rNNNN poison"
