# FortranCallGraph configuration for the n4_umn_pes region.
# Pass this file explicitly with -cf.
# NOTE: FCG exec()s this file, so __file__ would resolve to FCG's own tree —
# paths must be absolute, not derived from __file__.

BASE = '/home/adolgert/dev/skateboard/tools/regionharness/cases/n4_umn_pes/fcg'

CACHE_DIR = BASE + '/cache'
ASSEMBLER_DIRS = [BASE + '/asm']
SOURCE_DIRS = ['/home/adolgert/dev/skateboard/codes/CoarseAIR/src/PESs',
               '/home/adolgert/dev/skateboard/codes/CoarseAIR/src/Parameters']
SPECIAL_MODULE_FILES = {}
# Keep empty: FCG has a latent bug (globals.py:92, missing call parens) that
# makes a non-empty EXCLUDE_MODULES misbehave.
EXCLUDE_MODULES = []
IGNORE_GLOBALS_FROM_MODULES = []
IGNORE_DERIVED_TYPES = []

# If FCG's regex parser chokes on the cpp'd .F90 sources, switch to the
# preprocessed copies generated by make_asm.sh:
# SOURCE_DIRS = [BASE + '/pre']
# SOURCE_FILES_PREPROCESSED = True
